print("Welcome to the tip calculator!\n")
bill = float(input("What was the total bill? $\n"))
tip = int(input("What percentage tip would you like to give? 10 12 15 \n"))
people = int(input("How many people to split the bill? \n"))
calculation = round(bill * (1.0 + tip / 100) / people,2)
print(f"each person should pay: {calculation} ")
